import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Syne } from '@next/font/google';
import { AppProps } from 'next/app';
import './globals.css'

const syne = Syne({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Contacts-management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={syne.className}>{children}</body>
    </html>
  )
}
